### ISSUE TITLE
[Feature Request] Menu on either side

### ISSUE THREAD

**Issue by DasKatzchen** [Jophire/Tabletop-Simulator-Workshop-Items#2]
I think you're already contemplating this, but it would be helpful if the menu appeared when the card was placed face down, in order to activate functions like Morph. Would also be useful for other card games that involve placing cards face down, such as Yu-Gi-Oh. I might play around with it and make a pull request

**Comment by Jophire** [comment]
Will push a new build where the buttons automatically reflect the cards orientation as a test.

**Comment by Jophire** [comment]
Sadly unable to implement this at this time due to how cards and card like objects handle face down and face up.
While face down, cards do not render any buttons or card info such as name as long as object.hide_when_face_down is true.
If I force that value to false, cards can render buttons while face down, which is how the current flip button functions, however, it also reveals card properties such as its name. The morph module bypasses this by setting the cards name to morph until it is unmorphed, however constantly checking the cards state for its orientation to automatically hide the cards name would have potential impact on game play depending on the amount of encoded objects.

Will contemplate other solutions for now.

**Comment by Jophire** [comment]
I entirely forgot that context menu was now a thing. Added a context menu for flipping the menu.
